export {
  acceptDocumentProposal,
  createAgentDocumentProposal,
  createBlockDocumentProposal,
  createBlockDocumentProposalOperations,
  createLearningItemFromFinding,
  createReviewDocumentProposals,
  createSkillSelectionRun,
  createSelectionDocumentProposal,
  dismissReviewFinding,
  loadPageDocumentProposals,
  rejectDocumentProposal,
  recordReadOnlyAiAction,
  startAiActionRun,
  completeAiActionRun,
  type PageDocumentProposal,
  type BlockProposalBehavior,
  type CreateAgentDocumentProposalInput,
  type ReviewFindingDraft,
  type SelectionProposalSegment,
} from "./lib/document-proposals";
export {
  isDocumentProposalStale,
  type DocumentProposalSnapshot,
} from "./lifecycle";
