export {
  BLOCK_ID_ATTRIBUTE,
  createDocumentEditorExtensions,
  DocumentCodeBlock,
  DocumentEditorError,
  plainTextFromDocumentBlocks,
  prepareDocumentContent,
  type DocumentContent,
} from "./lib/schema";
export {
  applyDocumentOperations,
  applyDocumentOperationsToEditor,
  createDocumentTextIndex,
  createDocumentEditorSession,
  createPortableExcerpt,
  DocumentOperationError,
  type AllowedBlockAttributes,
  type AppliedDocumentOperations,
  type DocumentOperation,
  type DocumentOperationBatch,
  type DocumentTextBlock,
  type DocumentTextIndex,
  type DocumentTarget,
  type PortableExcerpt,
  type TextReplacementTarget,
} from "./lib/operations";
